### ISSUE TITLE
3D games drawing issue

### ISSUE THREAD

**Issue by TheEnderface** [nikita36078/J2ME-Loader#126]
Some java 3D m3g file loader show multiple buffering, and when we look around

**Comment by AdityaMH** [comment]
Since "draw buffer clearing" was deleted in newest version. i think that's impossible to remove buffer in some games. even i can't playing revival 2 nicely because this issue.

**Comment by nikita36078** [comment]
I deleted draw buffer clearing since I fixed most issues where it could help. M3G bug isn't connected with it.
@AdityaMH, are you sure that you use latest version of the emulator? I don't see that bug in 1.2.7.5.

**Comment by AdityaMH** [comment]
i always using latest version for testing update. I tested Revival 2 version 1.5.20, multiscreen touchscreen. but screen still showed title menu even game on selecting clan.

**Comment by nikita36078** [comment]
@AdityaMH Revival 2 fixed now.

**Comment by AdityaMH** [comment]
Thanks, that great. but still have bug about Revival 2. when input name or city name, misleading letters will appear when clicking uncapitalized letter or number.

**Comment by nikita36078** [comment]
I think it will be better to create issue for each game with such bug.
